USE PORTLIB
REAL X, Y
INTEGER PONTO, PONTOS, VER
WRITE(*,*) "Entre com o numero de pontos"
READ(*,*) PONTOS
OPEN(7, FILE= "DADOS-2.TXT")
DO PONTO = 1, PONTOS
X = PONTO - 1
Y = X**3
WRITE(7,40) X, Y
40 FORMAT( 2 ( 1PE10.2 ) )
END DO
CLOSE(7)
VER = SYSTEM ("Notepad DADOS-2.TXT")
VER = SYSTEM ("CMD")
VER = SYSTEM ("WGNUPLOT COMANDOS-2.TXT")
END