FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        avahi-daemon \
        dbus \
    && rm -rf /var/lib/apt/lists/*

COPY avahi-service.xml /etc/avahi/services/gfig.service

# Script para iniciar dbus e avahi
RUN echo '#!/bin/bash\n\
mkdir -p /run/dbus\n\
dbus-daemon --system --nofork &\n\
sleep 1\n\
exec avahi-daemon --no-rlimits\n\
' > /start.sh && chmod +x /start.sh

EXPOSE 5353/udp

CMD ["/start.sh"]
