FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        avahi-daemon \
    && apt-get remove -y dbus dbus-bin dbus-daemon libdbus-1-3 \
    && rm -rf /var/lib/apt/lists/*

COPY avahi-service.xml /etc/avahi/services/gfig.service

EXPOSE 5353/udp

CMD ["avahi-daemon", "--no-rlimits"]
