PROGRAM PROGRAMA102b
   USE PORTLIB
   INTEGER LINHA, LINHAS, COLUNA, COLUNAS, CONSTANTE, VER
   REAL,ALLOCATABLE,DIMENSION(:,:) :: MATRIZ_A, MATRIZ_B, MATRIZ_C
   WRITE(*,*) "Entre com o valor da CONSTANTE (inteiro)"
   READ(*,*) CONSTANTE
   WRITE(*,*) "Entre com o numero de linhas das matrizes (inteiro)"
   READ(*,*) LINHAS
   WRITE(*,*) "Entre com o numero de colunas das matrizes (inteiro)"
   READ(*,*) COLUNAS
   ALLOCATE ( MATRIZ_A(LINHAS,COLUNAS), MATRIZ_B(LINHAS,COLUNAS), &
      MATRIZ_C(LINHAS,COLUNAS) )
   DO LINHA = 1, LINHAS
      WRITE(*,*) "Entre com os valores dos elementos da MATRIZ_A da linha =", LINHA
      READ(*,*) ( MATRIZ_A(LINHA,COLUNA), COLUNA = 1, COLUNAS )
   END DO
   DO LINHA = 1, LINHAS
      DO COLUNA = 1, COLUNAS
         MATRIZ_B(LINHA,COLUNA) = CONSTANTE * MATRIZ_A(LINHA,COLUNA)
      END DO
   END DO
   DO LINHA = 1, LINHAS

      DO COLUNA = 1, COLUNAS
         MATRIZ_C(LINHA,COLUNA) = MATRIZ_A(LINHA,COLUNA) + MATRIZ_B(LINHA,COLUNA)
      END DO
   END DO
   OPEN(10, FILE="SAIDA10B.TXT")
   WRITE(10,31) CONSTANTE
31 FORMAT("CONSTANTE = ", I5, /)
   WRITE(10,32)
32 FORMAT(3X, "*** MATRIZ_A (dados) ***")
   DO LINHA = 1, LINHAS
      WRITE(10,33) ( MATRIZ_A(LINHA,COLUNA), COLUNA = 1, COLUNAS )
33    FORMAT( 10 (3X, 1PE10.3 ) )
   END DO
   WRITE(10,41)
41 FORMAT(1/, 3X, "*** MATRIZ_B (CONSTANTE * MATRIZ_A) ***")
   DO LINHA = 1, LINHAS
      WRITE(10,33) ( MATRIZ_B(LINHA,COLUNA), COLUNA = 1, COLUNAS )
   END DO
   WRITE(10,51)
51 FORMAT(1/, 3X, "*** MATRIZ_C (MATRIZ_A + MATRIZ_B) ***")
   DO LINHA = 1, LINHAS
      WRITE(10,33) ( MATRIZ_C(LINHA,COLUNA), COLUNA = 1, COLUNAS )
   END DO
   CLOSE(10)
   VER = SYSTEM("Notepad SAIDA10B.TXT")
END PROGRAM PROGRAMA102b
