PROGRAM programa9_4
IMPLICIT NONE 
INTEGER ::QUANTIDADE_ELEMENTOS,ELEMENTO
REAL , ALLOCATABLE, DIMENSION(:) :: CONJUNTO_A, CONJUNTO_B, CONJUNTO_C


WRITE(*,*) "Entre com a quantidade de elementos do CONJUNTO_A"
QUANTIDADE_ELEMENTOS=3

ALLOCATE ( CONJUNTO_A(QUANTIDADE_ELEMENTOS) , &
		   CONJUNTO_B(QUANTIDADE_ELEMENTOS) , &
		   CONJUNTO_C(QUANTIDADE_ELEMENTOS)  )
		  

WRITE (*,*) "Entre com os valores do conjunto_a"

call random_seed()


DO ELEMENTO=1, QUANTIDADE_ELEMENTOS
	call random_number(CONJUNTO_A(elemento))
END DO; 

CONJUNTO_B=CONJUNTO_A+10

CONJUNTO_C=EXP(CONJUNTO_A)

WRITE(*,*) "CONJUNTO_B = ", CONJUNTO_B

DO ELEMENTO = 1, QUANTIDADE_ELEMENTOS
	WRITE(*,20) ELEMENTO, CONJUNTO_C(ELEMENTO)
	20 FORMAT(10X, "CONJUNTO_C(", I2, ") = ", 1PE15.3 )
END DO




END PROGRAM programa9_4